version: '3.8'
services:
  flask_app:
    build: ./flask_app
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - nginx  # Make Flask depend on NGINX for networking reasons

  websocket_server1:
    build: ./websocket_server
    depends_on:
      - redis

  websocket_server2:
    build: ./websocket_server
    depends_on:
      - redis

  websocket_server3:
    build: ./websocket_server
    depends_on:
      - redis

  nginx:
      image: nginx:latest
      ports:
        - "80:80"  # For HTTP and WebSocket
        - "81:81"  # For TCP traffic
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - websocket_server1
        - websocket_server2
        - websocket_server3



  redis:
    image: redis:latest
    ports:
      - "6379:6379"
